spring:
  datasource:
    url: "jdbc:mysql://192.168.0.111:3306/invest-sim"
    driver-class-name: com.mysql.jdbc.Driver
    username: invest-sim
    password: RITyBonEtRym
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  jooq:
    sql-dialect: org.hibernate.dialect.MySQLDialect

stocks:
  api:
    key: RA3MEL2DG6O9ZJ8T