spring:
  datasource:
    url: "jdbc:postgresql://192.168.0.111/postgres"
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: Laptopfoxes57$
    dbcp2:
      driver-class-name: org.postgresql.Driver
    hikari:
      driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: create
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  jooq:
    sql-dialect: org.hibernate.dialect.PostgreSQLDialect
